/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * RigArchitect API
 * API documentation for RigArchitect application
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ComponentRequest,
  ComponentResponse,
  GetAllComponentsPagedParams,
  GetComponentsByBrandPagedParams,
  GetComponentsByTypePagedParams,
  GetComponentsInStockPagedParams,
  GetComponentsInStockParams,
  MessageResponse,
  PagedResponseComponentResponse,
  SearchComponentsPagedParams,
  SearchComponentsParams
} from '.././model';





/**
 * Retrieve a single component using its ID
 * @summary Get a component by ID
 */
export const getComponentById = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ComponentResponse>> => {
    
    
    return axios.default.get(
      `/api/v1/components/${id}`,options
    );
  }


export const getGetComponentByIdQueryKey = (id?: number,) => {
    return [`/api/v1/components/${id}`] as const;
    }

    
export const getGetComponentByIdQueryOptions = <TData = Awaited<ReturnType<typeof getComponentById>>, TError = AxiosError<ComponentResponse>>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComponentById>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetComponentByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getComponentById>>> = ({ signal }) => getComponentById(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getComponentById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetComponentByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getComponentById>>>
export type GetComponentByIdQueryError = AxiosError<ComponentResponse>


export function useGetComponentById<TData = Awaited<ReturnType<typeof getComponentById>>, TError = AxiosError<ComponentResponse>>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComponentById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getComponentById>>,
          TError,
          Awaited<ReturnType<typeof getComponentById>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetComponentById<TData = Awaited<ReturnType<typeof getComponentById>>, TError = AxiosError<ComponentResponse>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComponentById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getComponentById>>,
          TError,
          Awaited<ReturnType<typeof getComponentById>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetComponentById<TData = Awaited<ReturnType<typeof getComponentById>>, TError = AxiosError<ComponentResponse>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComponentById>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a component by ID
 */

export function useGetComponentById<TData = Awaited<ReturnType<typeof getComponentById>>, TError = AxiosError<ComponentResponse>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComponentById>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetComponentByIdQueryOptions(id,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Update a component in the catalog
 * @summary Update an existing component
 */
export const updateComponent = (
    id: number,
    componentRequest: ComponentRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ComponentResponse>> => {
    
    
    return axios.default.put(
      `/api/v1/components/${id}`,
      componentRequest,options
    );
  }



export const getUpdateComponentMutationOptions = <TError = AxiosError<ComponentResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateComponent>>, TError,{id: number;data: ComponentRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateComponent>>, TError,{id: number;data: ComponentRequest}, TContext> => {

const mutationKey = ['updateComponent'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateComponent>>, {id: number;data: ComponentRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateComponent(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateComponentMutationResult = NonNullable<Awaited<ReturnType<typeof updateComponent>>>
    export type UpdateComponentMutationBody = ComponentRequest
    export type UpdateComponentMutationError = AxiosError<ComponentResponse>

    /**
 * @summary Update an existing component
 */
export const useUpdateComponent = <TError = AxiosError<ComponentResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateComponent>>, TError,{id: number;data: ComponentRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateComponent>>,
        TError,
        {id: number;data: ComponentRequest},
        TContext
      > => {

      const mutationOptions = getUpdateComponentMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * Remove a component from the catalog
 * @summary Delete a component
 */
export const deleteComponent = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<MessageResponse>> => {
    
    
    return axios.default.delete(
      `/api/v1/components/${id}`,options
    );
  }



export const getDeleteComponentMutationOptions = <TError = AxiosError<MessageResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteComponent>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteComponent>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteComponent'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteComponent>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteComponent(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteComponentMutationResult = NonNullable<Awaited<ReturnType<typeof deleteComponent>>>
    
    export type DeleteComponentMutationError = AxiosError<MessageResponse>

    /**
 * @summary Delete a component
 */
export const useDeleteComponent = <TError = AxiosError<MessageResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteComponent>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteComponent>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteComponentMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * Retrieve all components in the catalog (non-paginated)
 * @summary Get all components
 */
export const getAllComponents = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ComponentResponse[]>> => {
    
    
    return axios.default.get(
      `/api/v1/components`,options
    );
  }


export const getGetAllComponentsQueryKey = () => {
    return [`/api/v1/components`] as const;
    }

    
export const getGetAllComponentsQueryOptions = <TData = Awaited<ReturnType<typeof getAllComponents>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllComponents>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllComponentsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllComponents>>> = ({ signal }) => getAllComponents({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllComponents>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllComponentsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllComponents>>>
export type GetAllComponentsQueryError = AxiosError<unknown>


export function useGetAllComponents<TData = Awaited<ReturnType<typeof getAllComponents>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllComponents>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllComponents>>,
          TError,
          Awaited<ReturnType<typeof getAllComponents>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllComponents<TData = Awaited<ReturnType<typeof getAllComponents>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllComponents>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllComponents>>,
          TError,
          Awaited<ReturnType<typeof getAllComponents>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllComponents<TData = Awaited<ReturnType<typeof getAllComponents>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllComponents>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all components
 */

export function useGetAllComponents<TData = Awaited<ReturnType<typeof getAllComponents>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllComponents>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllComponentsQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Add a new component to the catalog
 * @summary Create a new component
 */
export const createComponent = (
    componentRequest: ComponentRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ComponentResponse>> => {
    
    
    return axios.default.post(
      `/api/v1/components`,
      componentRequest,options
    );
  }



export const getCreateComponentMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createComponent>>, TError,{data: ComponentRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createComponent>>, TError,{data: ComponentRequest}, TContext> => {

const mutationKey = ['createComponent'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createComponent>>, {data: ComponentRequest}> = (props) => {
          const {data} = props ?? {};

          return  createComponent(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateComponentMutationResult = NonNullable<Awaited<ReturnType<typeof createComponent>>>
    export type CreateComponentMutationBody = ComponentRequest
    export type CreateComponentMutationError = AxiosError<unknown>

    /**
 * @summary Create a new component
 */
export const useCreateComponent = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createComponent>>, TError,{data: ComponentRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createComponent>>,
        TError,
        {data: ComponentRequest},
        TContext
      > => {

      const mutationOptions = getCreateComponentMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * Retrieve all components of a specific type (non-paginated)
 * @summary Get components by type
 */
export const getComponentsByType = (
    type: 'CPU' | 'GPU' | 'RAM' | 'SSD' | 'HDD' | 'Motherboard' | 'PSU' | 'Case' | 'Cooler', options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ComponentResponse[]>> => {
    
    
    return axios.default.get(
      `/api/v1/components/type/${type}`,options
    );
  }


export const getGetComponentsByTypeQueryKey = (type?: 'CPU' | 'GPU' | 'RAM' | 'SSD' | 'HDD' | 'Motherboard' | 'PSU' | 'Case' | 'Cooler',) => {
    return [`/api/v1/components/type/${type}`] as const;
    }

    
export const getGetComponentsByTypeQueryOptions = <TData = Awaited<ReturnType<typeof getComponentsByType>>, TError = AxiosError<unknown>>(type: 'CPU' | 'GPU' | 'RAM' | 'SSD' | 'HDD' | 'Motherboard' | 'PSU' | 'Case' | 'Cooler', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComponentsByType>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetComponentsByTypeQueryKey(type);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getComponentsByType>>> = ({ signal }) => getComponentsByType(type, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(type), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getComponentsByType>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetComponentsByTypeQueryResult = NonNullable<Awaited<ReturnType<typeof getComponentsByType>>>
export type GetComponentsByTypeQueryError = AxiosError<unknown>


export function useGetComponentsByType<TData = Awaited<ReturnType<typeof getComponentsByType>>, TError = AxiosError<unknown>>(
 type: 'CPU' | 'GPU' | 'RAM' | 'SSD' | 'HDD' | 'Motherboard' | 'PSU' | 'Case' | 'Cooler', options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComponentsByType>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getComponentsByType>>,
          TError,
          Awaited<ReturnType<typeof getComponentsByType>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetComponentsByType<TData = Awaited<ReturnType<typeof getComponentsByType>>, TError = AxiosError<unknown>>(
 type: 'CPU' | 'GPU' | 'RAM' | 'SSD' | 'HDD' | 'Motherboard' | 'PSU' | 'Case' | 'Cooler', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComponentsByType>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getComponentsByType>>,
          TError,
          Awaited<ReturnType<typeof getComponentsByType>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetComponentsByType<TData = Awaited<ReturnType<typeof getComponentsByType>>, TError = AxiosError<unknown>>(
 type: 'CPU' | 'GPU' | 'RAM' | 'SSD' | 'HDD' | 'Motherboard' | 'PSU' | 'Case' | 'Cooler', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComponentsByType>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get components by type
 */

export function useGetComponentsByType<TData = Awaited<ReturnType<typeof getComponentsByType>>, TError = AxiosError<unknown>>(
 type: 'CPU' | 'GPU' | 'RAM' | 'SSD' | 'HDD' | 'Motherboard' | 'PSU' | 'Case' | 'Cooler', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComponentsByType>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetComponentsByTypeQueryOptions(type,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Retrieve components of a specific type with pagination
 * @summary Get components by type (paginated)
 */
export const getComponentsByTypePaged = (
    type: 'CPU' | 'GPU' | 'RAM' | 'SSD' | 'HDD' | 'Motherboard' | 'PSU' | 'Case' | 'Cooler',
    params?: GetComponentsByTypePagedParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PagedResponseComponentResponse>> => {
    
    
    return axios.default.get(
      `/api/v1/components/type/${type}/paged`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getGetComponentsByTypePagedQueryKey = (type?: 'CPU' | 'GPU' | 'RAM' | 'SSD' | 'HDD' | 'Motherboard' | 'PSU' | 'Case' | 'Cooler',
    params?: GetComponentsByTypePagedParams,) => {
    return [`/api/v1/components/type/${type}/paged`, ...(params ? [params]: [])] as const;
    }

    
export const getGetComponentsByTypePagedQueryOptions = <TData = Awaited<ReturnType<typeof getComponentsByTypePaged>>, TError = AxiosError<unknown>>(type: 'CPU' | 'GPU' | 'RAM' | 'SSD' | 'HDD' | 'Motherboard' | 'PSU' | 'Case' | 'Cooler',
    params?: GetComponentsByTypePagedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComponentsByTypePaged>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetComponentsByTypePagedQueryKey(type,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getComponentsByTypePaged>>> = ({ signal }) => getComponentsByTypePaged(type,params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(type), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getComponentsByTypePaged>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetComponentsByTypePagedQueryResult = NonNullable<Awaited<ReturnType<typeof getComponentsByTypePaged>>>
export type GetComponentsByTypePagedQueryError = AxiosError<unknown>


export function useGetComponentsByTypePaged<TData = Awaited<ReturnType<typeof getComponentsByTypePaged>>, TError = AxiosError<unknown>>(
 type: 'CPU' | 'GPU' | 'RAM' | 'SSD' | 'HDD' | 'Motherboard' | 'PSU' | 'Case' | 'Cooler',
    params: undefined |  GetComponentsByTypePagedParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComponentsByTypePaged>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getComponentsByTypePaged>>,
          TError,
          Awaited<ReturnType<typeof getComponentsByTypePaged>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetComponentsByTypePaged<TData = Awaited<ReturnType<typeof getComponentsByTypePaged>>, TError = AxiosError<unknown>>(
 type: 'CPU' | 'GPU' | 'RAM' | 'SSD' | 'HDD' | 'Motherboard' | 'PSU' | 'Case' | 'Cooler',
    params?: GetComponentsByTypePagedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComponentsByTypePaged>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getComponentsByTypePaged>>,
          TError,
          Awaited<ReturnType<typeof getComponentsByTypePaged>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetComponentsByTypePaged<TData = Awaited<ReturnType<typeof getComponentsByTypePaged>>, TError = AxiosError<unknown>>(
 type: 'CPU' | 'GPU' | 'RAM' | 'SSD' | 'HDD' | 'Motherboard' | 'PSU' | 'Case' | 'Cooler',
    params?: GetComponentsByTypePagedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComponentsByTypePaged>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get components by type (paginated)
 */

export function useGetComponentsByTypePaged<TData = Awaited<ReturnType<typeof getComponentsByTypePaged>>, TError = AxiosError<unknown>>(
 type: 'CPU' | 'GPU' | 'RAM' | 'SSD' | 'HDD' | 'Motherboard' | 'PSU' | 'Case' | 'Cooler',
    params?: GetComponentsByTypePagedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComponentsByTypePaged>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetComponentsByTypePagedQueryOptions(type,params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Retrieve components filtered by socket type
 * @summary Get components by socket
 */
export const getComponentsBySocket = (
    socket: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ComponentResponse[]>> => {
    
    
    return axios.default.get(
      `/api/v1/components/socket/${socket}`,options
    );
  }


export const getGetComponentsBySocketQueryKey = (socket?: string,) => {
    return [`/api/v1/components/socket/${socket}`] as const;
    }

    
export const getGetComponentsBySocketQueryOptions = <TData = Awaited<ReturnType<typeof getComponentsBySocket>>, TError = AxiosError<unknown>>(socket: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComponentsBySocket>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetComponentsBySocketQueryKey(socket);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getComponentsBySocket>>> = ({ signal }) => getComponentsBySocket(socket, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(socket), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getComponentsBySocket>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetComponentsBySocketQueryResult = NonNullable<Awaited<ReturnType<typeof getComponentsBySocket>>>
export type GetComponentsBySocketQueryError = AxiosError<unknown>


export function useGetComponentsBySocket<TData = Awaited<ReturnType<typeof getComponentsBySocket>>, TError = AxiosError<unknown>>(
 socket: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComponentsBySocket>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getComponentsBySocket>>,
          TError,
          Awaited<ReturnType<typeof getComponentsBySocket>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetComponentsBySocket<TData = Awaited<ReturnType<typeof getComponentsBySocket>>, TError = AxiosError<unknown>>(
 socket: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComponentsBySocket>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getComponentsBySocket>>,
          TError,
          Awaited<ReturnType<typeof getComponentsBySocket>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetComponentsBySocket<TData = Awaited<ReturnType<typeof getComponentsBySocket>>, TError = AxiosError<unknown>>(
 socket: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComponentsBySocket>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get components by socket
 */

export function useGetComponentsBySocket<TData = Awaited<ReturnType<typeof getComponentsBySocket>>, TError = AxiosError<unknown>>(
 socket: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComponentsBySocket>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetComponentsBySocketQueryOptions(socket,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Search components using multiple optional filters
 * @summary Search components
 */
export const searchComponents = (
    params?: SearchComponentsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ComponentResponse[]>> => {
    
    
    return axios.default.get(
      `/api/v1/components/search`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getSearchComponentsQueryKey = (params?: SearchComponentsParams,) => {
    return [`/api/v1/components/search`, ...(params ? [params]: [])] as const;
    }

    
export const getSearchComponentsQueryOptions = <TData = Awaited<ReturnType<typeof searchComponents>>, TError = AxiosError<unknown>>(params?: SearchComponentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchComponents>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchComponentsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchComponents>>> = ({ signal }) => searchComponents(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchComponents>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchComponentsQueryResult = NonNullable<Awaited<ReturnType<typeof searchComponents>>>
export type SearchComponentsQueryError = AxiosError<unknown>


export function useSearchComponents<TData = Awaited<ReturnType<typeof searchComponents>>, TError = AxiosError<unknown>>(
 params: undefined |  SearchComponentsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchComponents>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchComponents>>,
          TError,
          Awaited<ReturnType<typeof searchComponents>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchComponents<TData = Awaited<ReturnType<typeof searchComponents>>, TError = AxiosError<unknown>>(
 params?: SearchComponentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchComponents>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchComponents>>,
          TError,
          Awaited<ReturnType<typeof searchComponents>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchComponents<TData = Awaited<ReturnType<typeof searchComponents>>, TError = AxiosError<unknown>>(
 params?: SearchComponentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchComponents>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Search components
 */

export function useSearchComponents<TData = Awaited<ReturnType<typeof searchComponents>>, TError = AxiosError<unknown>>(
 params?: SearchComponentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchComponents>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchComponentsQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Search components with multiple filters and pagination
 * @summary Search components (paginated)
 */
export const searchComponentsPaged = (
    params?: SearchComponentsPagedParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PagedResponseComponentResponse>> => {
    
    
    return axios.default.get(
      `/api/v1/components/search/paged`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getSearchComponentsPagedQueryKey = (params?: SearchComponentsPagedParams,) => {
    return [`/api/v1/components/search/paged`, ...(params ? [params]: [])] as const;
    }

    
export const getSearchComponentsPagedQueryOptions = <TData = Awaited<ReturnType<typeof searchComponentsPaged>>, TError = AxiosError<unknown>>(params?: SearchComponentsPagedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchComponentsPaged>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchComponentsPagedQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchComponentsPaged>>> = ({ signal }) => searchComponentsPaged(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchComponentsPaged>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchComponentsPagedQueryResult = NonNullable<Awaited<ReturnType<typeof searchComponentsPaged>>>
export type SearchComponentsPagedQueryError = AxiosError<unknown>


export function useSearchComponentsPaged<TData = Awaited<ReturnType<typeof searchComponentsPaged>>, TError = AxiosError<unknown>>(
 params: undefined |  SearchComponentsPagedParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchComponentsPaged>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchComponentsPaged>>,
          TError,
          Awaited<ReturnType<typeof searchComponentsPaged>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchComponentsPaged<TData = Awaited<ReturnType<typeof searchComponentsPaged>>, TError = AxiosError<unknown>>(
 params?: SearchComponentsPagedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchComponentsPaged>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchComponentsPaged>>,
          TError,
          Awaited<ReturnType<typeof searchComponentsPaged>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchComponentsPaged<TData = Awaited<ReturnType<typeof searchComponentsPaged>>, TError = AxiosError<unknown>>(
 params?: SearchComponentsPagedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchComponentsPaged>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Search components (paginated)
 */

export function useSearchComponentsPaged<TData = Awaited<ReturnType<typeof searchComponentsPaged>>, TError = AxiosError<unknown>>(
 params?: SearchComponentsPagedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchComponentsPaged>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchComponentsPagedQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Retrieve all components with pagination support
 * @summary Get all components (paginated)
 */
export const getAllComponentsPaged = (
    params?: GetAllComponentsPagedParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PagedResponseComponentResponse>> => {
    
    
    return axios.default.get(
      `/api/v1/components/paged`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getGetAllComponentsPagedQueryKey = (params?: GetAllComponentsPagedParams,) => {
    return [`/api/v1/components/paged`, ...(params ? [params]: [])] as const;
    }

    
export const getGetAllComponentsPagedQueryOptions = <TData = Awaited<ReturnType<typeof getAllComponentsPaged>>, TError = AxiosError<unknown>>(params?: GetAllComponentsPagedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllComponentsPaged>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllComponentsPagedQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllComponentsPaged>>> = ({ signal }) => getAllComponentsPaged(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllComponentsPaged>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllComponentsPagedQueryResult = NonNullable<Awaited<ReturnType<typeof getAllComponentsPaged>>>
export type GetAllComponentsPagedQueryError = AxiosError<unknown>


export function useGetAllComponentsPaged<TData = Awaited<ReturnType<typeof getAllComponentsPaged>>, TError = AxiosError<unknown>>(
 params: undefined |  GetAllComponentsPagedParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllComponentsPaged>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllComponentsPaged>>,
          TError,
          Awaited<ReturnType<typeof getAllComponentsPaged>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllComponentsPaged<TData = Awaited<ReturnType<typeof getAllComponentsPaged>>, TError = AxiosError<unknown>>(
 params?: GetAllComponentsPagedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllComponentsPaged>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllComponentsPaged>>,
          TError,
          Awaited<ReturnType<typeof getAllComponentsPaged>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllComponentsPaged<TData = Awaited<ReturnType<typeof getAllComponentsPaged>>, TError = AxiosError<unknown>>(
 params?: GetAllComponentsPagedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllComponentsPaged>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all components (paginated)
 */

export function useGetAllComponentsPaged<TData = Awaited<ReturnType<typeof getAllComponentsPaged>>, TError = AxiosError<unknown>>(
 params?: GetAllComponentsPagedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllComponentsPaged>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllComponentsPagedQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Retrieve components with at least minQuantity in stock
 * @summary Get components in stock
 */
export const getComponentsInStock = (
    params?: GetComponentsInStockParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ComponentResponse[]>> => {
    
    
    return axios.default.get(
      `/api/v1/components/in-stock`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getGetComponentsInStockQueryKey = (params?: GetComponentsInStockParams,) => {
    return [`/api/v1/components/in-stock`, ...(params ? [params]: [])] as const;
    }

    
export const getGetComponentsInStockQueryOptions = <TData = Awaited<ReturnType<typeof getComponentsInStock>>, TError = AxiosError<unknown>>(params?: GetComponentsInStockParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComponentsInStock>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetComponentsInStockQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getComponentsInStock>>> = ({ signal }) => getComponentsInStock(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getComponentsInStock>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetComponentsInStockQueryResult = NonNullable<Awaited<ReturnType<typeof getComponentsInStock>>>
export type GetComponentsInStockQueryError = AxiosError<unknown>


export function useGetComponentsInStock<TData = Awaited<ReturnType<typeof getComponentsInStock>>, TError = AxiosError<unknown>>(
 params: undefined |  GetComponentsInStockParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComponentsInStock>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getComponentsInStock>>,
          TError,
          Awaited<ReturnType<typeof getComponentsInStock>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetComponentsInStock<TData = Awaited<ReturnType<typeof getComponentsInStock>>, TError = AxiosError<unknown>>(
 params?: GetComponentsInStockParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComponentsInStock>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getComponentsInStock>>,
          TError,
          Awaited<ReturnType<typeof getComponentsInStock>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetComponentsInStock<TData = Awaited<ReturnType<typeof getComponentsInStock>>, TError = AxiosError<unknown>>(
 params?: GetComponentsInStockParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComponentsInStock>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get components in stock
 */

export function useGetComponentsInStock<TData = Awaited<ReturnType<typeof getComponentsInStock>>, TError = AxiosError<unknown>>(
 params?: GetComponentsInStockParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComponentsInStock>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetComponentsInStockQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Retrieve components in stock with pagination
 * @summary Get components in stock (paginated)
 */
export const getComponentsInStockPaged = (
    params?: GetComponentsInStockPagedParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PagedResponseComponentResponse>> => {
    
    
    return axios.default.get(
      `/api/v1/components/in-stock/paged`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getGetComponentsInStockPagedQueryKey = (params?: GetComponentsInStockPagedParams,) => {
    return [`/api/v1/components/in-stock/paged`, ...(params ? [params]: [])] as const;
    }

    
export const getGetComponentsInStockPagedQueryOptions = <TData = Awaited<ReturnType<typeof getComponentsInStockPaged>>, TError = AxiosError<unknown>>(params?: GetComponentsInStockPagedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComponentsInStockPaged>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetComponentsInStockPagedQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getComponentsInStockPaged>>> = ({ signal }) => getComponentsInStockPaged(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getComponentsInStockPaged>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetComponentsInStockPagedQueryResult = NonNullable<Awaited<ReturnType<typeof getComponentsInStockPaged>>>
export type GetComponentsInStockPagedQueryError = AxiosError<unknown>


export function useGetComponentsInStockPaged<TData = Awaited<ReturnType<typeof getComponentsInStockPaged>>, TError = AxiosError<unknown>>(
 params: undefined |  GetComponentsInStockPagedParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComponentsInStockPaged>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getComponentsInStockPaged>>,
          TError,
          Awaited<ReturnType<typeof getComponentsInStockPaged>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetComponentsInStockPaged<TData = Awaited<ReturnType<typeof getComponentsInStockPaged>>, TError = AxiosError<unknown>>(
 params?: GetComponentsInStockPagedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComponentsInStockPaged>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getComponentsInStockPaged>>,
          TError,
          Awaited<ReturnType<typeof getComponentsInStockPaged>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetComponentsInStockPaged<TData = Awaited<ReturnType<typeof getComponentsInStockPaged>>, TError = AxiosError<unknown>>(
 params?: GetComponentsInStockPagedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComponentsInStockPaged>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get components in stock (paginated)
 */

export function useGetComponentsInStockPaged<TData = Awaited<ReturnType<typeof getComponentsInStockPaged>>, TError = AxiosError<unknown>>(
 params?: GetComponentsInStockPagedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComponentsInStockPaged>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetComponentsInStockPagedQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Retrieve components filtered by compatibility tag
 * @summary Get components by compatibility tag
 */
export const getComponentsByCompatibilityTag = (
    tag: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ComponentResponse[]>> => {
    
    
    return axios.default.get(
      `/api/v1/components/compatibility/${tag}`,options
    );
  }


export const getGetComponentsByCompatibilityTagQueryKey = (tag?: string,) => {
    return [`/api/v1/components/compatibility/${tag}`] as const;
    }

    
export const getGetComponentsByCompatibilityTagQueryOptions = <TData = Awaited<ReturnType<typeof getComponentsByCompatibilityTag>>, TError = AxiosError<unknown>>(tag: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComponentsByCompatibilityTag>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetComponentsByCompatibilityTagQueryKey(tag);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getComponentsByCompatibilityTag>>> = ({ signal }) => getComponentsByCompatibilityTag(tag, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(tag), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getComponentsByCompatibilityTag>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetComponentsByCompatibilityTagQueryResult = NonNullable<Awaited<ReturnType<typeof getComponentsByCompatibilityTag>>>
export type GetComponentsByCompatibilityTagQueryError = AxiosError<unknown>


export function useGetComponentsByCompatibilityTag<TData = Awaited<ReturnType<typeof getComponentsByCompatibilityTag>>, TError = AxiosError<unknown>>(
 tag: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComponentsByCompatibilityTag>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getComponentsByCompatibilityTag>>,
          TError,
          Awaited<ReturnType<typeof getComponentsByCompatibilityTag>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetComponentsByCompatibilityTag<TData = Awaited<ReturnType<typeof getComponentsByCompatibilityTag>>, TError = AxiosError<unknown>>(
 tag: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComponentsByCompatibilityTag>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getComponentsByCompatibilityTag>>,
          TError,
          Awaited<ReturnType<typeof getComponentsByCompatibilityTag>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetComponentsByCompatibilityTag<TData = Awaited<ReturnType<typeof getComponentsByCompatibilityTag>>, TError = AxiosError<unknown>>(
 tag: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComponentsByCompatibilityTag>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get components by compatibility tag
 */

export function useGetComponentsByCompatibilityTag<TData = Awaited<ReturnType<typeof getComponentsByCompatibilityTag>>, TError = AxiosError<unknown>>(
 tag: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComponentsByCompatibilityTag>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetComponentsByCompatibilityTagQueryOptions(tag,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Retrieve all components from a specific brand
 * @summary Get components by brand
 */
export const getComponentsByBrand = (
    brand: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ComponentResponse[]>> => {
    
    
    return axios.default.get(
      `/api/v1/components/brand/${brand}`,options
    );
  }


export const getGetComponentsByBrandQueryKey = (brand?: string,) => {
    return [`/api/v1/components/brand/${brand}`] as const;
    }

    
export const getGetComponentsByBrandQueryOptions = <TData = Awaited<ReturnType<typeof getComponentsByBrand>>, TError = AxiosError<unknown>>(brand: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComponentsByBrand>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetComponentsByBrandQueryKey(brand);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getComponentsByBrand>>> = ({ signal }) => getComponentsByBrand(brand, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(brand), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getComponentsByBrand>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetComponentsByBrandQueryResult = NonNullable<Awaited<ReturnType<typeof getComponentsByBrand>>>
export type GetComponentsByBrandQueryError = AxiosError<unknown>


export function useGetComponentsByBrand<TData = Awaited<ReturnType<typeof getComponentsByBrand>>, TError = AxiosError<unknown>>(
 brand: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComponentsByBrand>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getComponentsByBrand>>,
          TError,
          Awaited<ReturnType<typeof getComponentsByBrand>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetComponentsByBrand<TData = Awaited<ReturnType<typeof getComponentsByBrand>>, TError = AxiosError<unknown>>(
 brand: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComponentsByBrand>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getComponentsByBrand>>,
          TError,
          Awaited<ReturnType<typeof getComponentsByBrand>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetComponentsByBrand<TData = Awaited<ReturnType<typeof getComponentsByBrand>>, TError = AxiosError<unknown>>(
 brand: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComponentsByBrand>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get components by brand
 */

export function useGetComponentsByBrand<TData = Awaited<ReturnType<typeof getComponentsByBrand>>, TError = AxiosError<unknown>>(
 brand: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComponentsByBrand>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetComponentsByBrandQueryOptions(brand,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Retrieve components by brand with pagination
 * @summary Get components by brand (paginated)
 */
export const getComponentsByBrandPaged = (
    brand: string,
    params?: GetComponentsByBrandPagedParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PagedResponseComponentResponse>> => {
    
    
    return axios.default.get(
      `/api/v1/components/brand/${brand}/paged`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getGetComponentsByBrandPagedQueryKey = (brand?: string,
    params?: GetComponentsByBrandPagedParams,) => {
    return [`/api/v1/components/brand/${brand}/paged`, ...(params ? [params]: [])] as const;
    }

    
export const getGetComponentsByBrandPagedQueryOptions = <TData = Awaited<ReturnType<typeof getComponentsByBrandPaged>>, TError = AxiosError<unknown>>(brand: string,
    params?: GetComponentsByBrandPagedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComponentsByBrandPaged>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetComponentsByBrandPagedQueryKey(brand,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getComponentsByBrandPaged>>> = ({ signal }) => getComponentsByBrandPaged(brand,params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(brand), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getComponentsByBrandPaged>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetComponentsByBrandPagedQueryResult = NonNullable<Awaited<ReturnType<typeof getComponentsByBrandPaged>>>
export type GetComponentsByBrandPagedQueryError = AxiosError<unknown>


export function useGetComponentsByBrandPaged<TData = Awaited<ReturnType<typeof getComponentsByBrandPaged>>, TError = AxiosError<unknown>>(
 brand: string,
    params: undefined |  GetComponentsByBrandPagedParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComponentsByBrandPaged>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getComponentsByBrandPaged>>,
          TError,
          Awaited<ReturnType<typeof getComponentsByBrandPaged>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetComponentsByBrandPaged<TData = Awaited<ReturnType<typeof getComponentsByBrandPaged>>, TError = AxiosError<unknown>>(
 brand: string,
    params?: GetComponentsByBrandPagedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComponentsByBrandPaged>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getComponentsByBrandPaged>>,
          TError,
          Awaited<ReturnType<typeof getComponentsByBrandPaged>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetComponentsByBrandPaged<TData = Awaited<ReturnType<typeof getComponentsByBrandPaged>>, TError = AxiosError<unknown>>(
 brand: string,
    params?: GetComponentsByBrandPagedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComponentsByBrandPaged>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get components by brand (paginated)
 */

export function useGetComponentsByBrandPaged<TData = Awaited<ReturnType<typeof getComponentsByBrandPaged>>, TError = AxiosError<unknown>>(
 brand: string,
    params?: GetComponentsByBrandPagedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComponentsByBrandPaged>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetComponentsByBrandPagedQueryOptions(brand,params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



