/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * RigArchitect API
 * API documentation for RigArchitect application
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  BuildCartRequest,
  BuildCartResponse,
  MessageResponse
} from '.././model';





/**
 * Returns a single build cart by its ID
 * @summary Get a cart by ID
 */
export const getCart = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<BuildCartResponse>> => {
    
    
    return axios.default.get(
      `/api/v1/carts/${id}`,options
    );
  }


export const getGetCartQueryKey = (id?: number,) => {
    return [`/api/v1/carts/${id}`] as const;
    }

    
export const getGetCartQueryOptions = <TData = Awaited<ReturnType<typeof getCart>>, TError = AxiosError<BuildCartResponse>>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCart>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCartQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCart>>> = ({ signal }) => getCart(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCart>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCartQueryResult = NonNullable<Awaited<ReturnType<typeof getCart>>>
export type GetCartQueryError = AxiosError<BuildCartResponse>


export function useGetCart<TData = Awaited<ReturnType<typeof getCart>>, TError = AxiosError<BuildCartResponse>>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCart>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCart>>,
          TError,
          Awaited<ReturnType<typeof getCart>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCart<TData = Awaited<ReturnType<typeof getCart>>, TError = AxiosError<BuildCartResponse>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCart>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCart>>,
          TError,
          Awaited<ReturnType<typeof getCart>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCart<TData = Awaited<ReturnType<typeof getCart>>, TError = AxiosError<BuildCartResponse>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCart>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a cart by ID
 */

export function useGetCart<TData = Awaited<ReturnType<typeof getCart>>, TError = AxiosError<BuildCartResponse>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCart>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCartQueryOptions(id,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Updates the name and status of a build cart
 * @summary Update a cart
 */
export const updateCart = (
    id: number,
    buildCartRequest: BuildCartRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<BuildCartResponse>> => {
    
    
    return axios.default.put(
      `/api/v1/carts/${id}`,
      buildCartRequest,options
    );
  }



export const getUpdateCartMutationOptions = <TError = AxiosError<BuildCartResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCart>>, TError,{id: number;data: BuildCartRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateCart>>, TError,{id: number;data: BuildCartRequest}, TContext> => {

const mutationKey = ['updateCart'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateCart>>, {id: number;data: BuildCartRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateCart(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateCartMutationResult = NonNullable<Awaited<ReturnType<typeof updateCart>>>
    export type UpdateCartMutationBody = BuildCartRequest
    export type UpdateCartMutationError = AxiosError<BuildCartResponse>

    /**
 * @summary Update a cart
 */
export const useUpdateCart = <TError = AxiosError<BuildCartResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCart>>, TError,{id: number;data: BuildCartRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateCart>>,
        TError,
        {id: number;data: BuildCartRequest},
        TContext
      > => {

      const mutationOptions = getUpdateCartMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * Deletes a build cart by ID
 * @summary Delete a cart
 */
export const deleteCart = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<MessageResponse>> => {
    
    
    return axios.default.delete(
      `/api/v1/carts/${id}`,options
    );
  }



export const getDeleteCartMutationOptions = <TError = AxiosError<MessageResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCart>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteCart>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteCart'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCart>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteCart(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteCartMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCart>>>
    
    export type DeleteCartMutationError = AxiosError<MessageResponse>

    /**
 * @summary Delete a cart
 */
export const useDeleteCart = <TError = AxiosError<MessageResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCart>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteCart>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteCartMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * Finalizes the build cart and updates user budget
 * @summary Finalize a cart
 */
export const finalizeCart = (
    cartId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string>> => {
    
    
    return axios.default.post(
      `/api/v1/carts/${cartId}/finalize`,undefined,{
        responseType: 'text',
    ...options,}
    );
  }



export const getFinalizeCartMutationOptions = <TError = AxiosError<string>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof finalizeCart>>, TError,{cartId: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof finalizeCart>>, TError,{cartId: number}, TContext> => {

const mutationKey = ['finalizeCart'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof finalizeCart>>, {cartId: number}> = (props) => {
          const {cartId} = props ?? {};

          return  finalizeCart(cartId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type FinalizeCartMutationResult = NonNullable<Awaited<ReturnType<typeof finalizeCart>>>
    
    export type FinalizeCartMutationError = AxiosError<string>

    /**
 * @summary Finalize a cart
 */
export const useFinalizeCart = <TError = AxiosError<string>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof finalizeCart>>, TError,{cartId: number}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof finalizeCart>>,
        TError,
        {cartId: number},
        TContext
      > => {

      const mutationOptions = getFinalizeCartMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * Returns all build carts for the specified user
 * @summary Get all carts for a user
 */
export const getUserCarts = (
    userId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<BuildCartResponse[]>> => {
    
    
    return axios.default.get(
      `/api/v1/carts/user/${userId}`,options
    );
  }


export const getGetUserCartsQueryKey = (userId?: number,) => {
    return [`/api/v1/carts/user/${userId}`] as const;
    }

    
export const getGetUserCartsQueryOptions = <TData = Awaited<ReturnType<typeof getUserCarts>>, TError = AxiosError<BuildCartResponse[]>>(userId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserCarts>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserCartsQueryKey(userId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserCarts>>> = ({ signal }) => getUserCarts(userId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(userId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserCarts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserCartsQueryResult = NonNullable<Awaited<ReturnType<typeof getUserCarts>>>
export type GetUserCartsQueryError = AxiosError<BuildCartResponse[]>


export function useGetUserCarts<TData = Awaited<ReturnType<typeof getUserCarts>>, TError = AxiosError<BuildCartResponse[]>>(
 userId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserCarts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserCarts>>,
          TError,
          Awaited<ReturnType<typeof getUserCarts>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserCarts<TData = Awaited<ReturnType<typeof getUserCarts>>, TError = AxiosError<BuildCartResponse[]>>(
 userId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserCarts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserCarts>>,
          TError,
          Awaited<ReturnType<typeof getUserCarts>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserCarts<TData = Awaited<ReturnType<typeof getUserCarts>>, TError = AxiosError<BuildCartResponse[]>>(
 userId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserCarts>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all carts for a user
 */

export function useGetUserCarts<TData = Awaited<ReturnType<typeof getUserCarts>>, TError = AxiosError<BuildCartResponse[]>>(
 userId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserCarts>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserCartsQueryOptions(userId,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Creates a new build cart for the specified user
 * @summary Create a cart for a user
 */
export const createCartForUser = (
    userId: number,
    buildCartRequest: BuildCartRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<BuildCartResponse>> => {
    
    
    return axios.default.post(
      `/api/v1/carts/user/${userId}`,
      buildCartRequest,options
    );
  }



export const getCreateCartForUserMutationOptions = <TError = AxiosError<BuildCartResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCartForUser>>, TError,{userId: number;data: BuildCartRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createCartForUser>>, TError,{userId: number;data: BuildCartRequest}, TContext> => {

const mutationKey = ['createCartForUser'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCartForUser>>, {userId: number;data: BuildCartRequest}> = (props) => {
          const {userId,data} = props ?? {};

          return  createCartForUser(userId,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateCartForUserMutationResult = NonNullable<Awaited<ReturnType<typeof createCartForUser>>>
    export type CreateCartForUserMutationBody = BuildCartRequest
    export type CreateCartForUserMutationError = AxiosError<BuildCartResponse>

    /**
 * @summary Create a cart for a user
 */
export const useCreateCartForUser = <TError = AxiosError<BuildCartResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCartForUser>>, TError,{userId: number;data: BuildCartRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createCartForUser>>,
        TError,
        {userId: number;data: BuildCartRequest},
        TContext
      > => {

      const mutationOptions = getCreateCartForUserMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    