/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * RigArchitect API
 * API documentation for RigArchitect application
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  GuestBuildRequest,
  GuestBuildResponse,
  GuestSessionRequest,
  GuestSessionResponse,
  MessageResponse
} from '.././model';





/**
 * Retrieve a guest build by its ID
 * @summary Get guest build
 */
export const getBuild = (
    buildId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GuestBuildResponse>> => {
    
    
    return axios.default.get(
      `/api/v1/guest/builds/${buildId}`,options
    );
  }


export const getGetBuildQueryKey = (buildId?: number,) => {
    return [`/api/v1/guest/builds/${buildId}`] as const;
    }

    
export const getGetBuildQueryOptions = <TData = Awaited<ReturnType<typeof getBuild>>, TError = AxiosError<GuestBuildResponse>>(buildId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBuild>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetBuildQueryKey(buildId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBuild>>> = ({ signal }) => getBuild(buildId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(buildId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getBuild>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetBuildQueryResult = NonNullable<Awaited<ReturnType<typeof getBuild>>>
export type GetBuildQueryError = AxiosError<GuestBuildResponse>


export function useGetBuild<TData = Awaited<ReturnType<typeof getBuild>>, TError = AxiosError<GuestBuildResponse>>(
 buildId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBuild>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBuild>>,
          TError,
          Awaited<ReturnType<typeof getBuild>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBuild<TData = Awaited<ReturnType<typeof getBuild>>, TError = AxiosError<GuestBuildResponse>>(
 buildId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBuild>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBuild>>,
          TError,
          Awaited<ReturnType<typeof getBuild>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBuild<TData = Awaited<ReturnType<typeof getBuild>>, TError = AxiosError<GuestBuildResponse>>(
 buildId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBuild>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get guest build
 */

export function useGetBuild<TData = Awaited<ReturnType<typeof getBuild>>, TError = AxiosError<GuestBuildResponse>>(
 buildId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBuild>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetBuildQueryOptions(buildId,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Update an existing guest build configuration
 * @summary Update guest build
 */
export const updateBuild = (
    buildId: number,
    guestBuildRequest: GuestBuildRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GuestBuildResponse>> => {
    
    
    return axios.default.put(
      `/api/v1/guest/builds/${buildId}`,
      guestBuildRequest,options
    );
  }



export const getUpdateBuildMutationOptions = <TError = AxiosError<GuestBuildResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateBuild>>, TError,{buildId: number;data: GuestBuildRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateBuild>>, TError,{buildId: number;data: GuestBuildRequest}, TContext> => {

const mutationKey = ['updateBuild'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateBuild>>, {buildId: number;data: GuestBuildRequest}> = (props) => {
          const {buildId,data} = props ?? {};

          return  updateBuild(buildId,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateBuildMutationResult = NonNullable<Awaited<ReturnType<typeof updateBuild>>>
    export type UpdateBuildMutationBody = GuestBuildRequest
    export type UpdateBuildMutationError = AxiosError<GuestBuildResponse>

    /**
 * @summary Update guest build
 */
export const useUpdateBuild = <TError = AxiosError<GuestBuildResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateBuild>>, TError,{buildId: number;data: GuestBuildRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateBuild>>,
        TError,
        {buildId: number;data: GuestBuildRequest},
        TContext
      > => {

      const mutationOptions = getUpdateBuildMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * Delete a guest build by its ID
 * @summary Delete guest build
 */
export const deleteBuild = (
    buildId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<MessageResponse>> => {
    
    
    return axios.default.delete(
      `/api/v1/guest/builds/${buildId}`,options
    );
  }



export const getDeleteBuildMutationOptions = <TError = AxiosError<MessageResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteBuild>>, TError,{buildId: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteBuild>>, TError,{buildId: number}, TContext> => {

const mutationKey = ['deleteBuild'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteBuild>>, {buildId: number}> = (props) => {
          const {buildId} = props ?? {};

          return  deleteBuild(buildId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteBuildMutationResult = NonNullable<Awaited<ReturnType<typeof deleteBuild>>>
    
    export type DeleteBuildMutationError = AxiosError<MessageResponse>

    /**
 * @summary Delete guest build
 */
export const useDeleteBuild = <TError = AxiosError<MessageResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteBuild>>, TError,{buildId: number}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteBuild>>,
        TError,
        {buildId: number},
        TContext
      > => {

      const mutationOptions = getDeleteBuildMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * Create a new guest session or retrieve existing one
 * @summary Create or get guest session
 */
export const createOrGetSession = (
    guestSessionRequest: GuestSessionRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GuestSessionResponse | GuestSessionResponse>> => {
    
    
    return axios.default.post(
      `/api/v1/guest/session`,
      guestSessionRequest,options
    );
  }



export const getCreateOrGetSessionMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createOrGetSession>>, TError,{data: GuestSessionRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createOrGetSession>>, TError,{data: GuestSessionRequest}, TContext> => {

const mutationKey = ['createOrGetSession'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createOrGetSession>>, {data: GuestSessionRequest}> = (props) => {
          const {data} = props ?? {};

          return  createOrGetSession(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateOrGetSessionMutationResult = NonNullable<Awaited<ReturnType<typeof createOrGetSession>>>
    export type CreateOrGetSessionMutationBody = GuestSessionRequest
    export type CreateOrGetSessionMutationError = AxiosError<unknown>

    /**
 * @summary Create or get guest session
 */
export const useCreateOrGetSession = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createOrGetSession>>, TError,{data: GuestSessionRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createOrGetSession>>,
        TError,
        {data: GuestSessionRequest},
        TContext
      > => {

      const mutationOptions = getCreateOrGetSessionMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * Extend the expiration time of a guest session
 * @summary Extend guest session
 */
export const extendSession = (
    sessionId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GuestSessionResponse>> => {
    
    
    return axios.default.post(
      `/api/v1/guest/session/${sessionId}/extend`,undefined,options
    );
  }



export const getExtendSessionMutationOptions = <TError = AxiosError<GuestSessionResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof extendSession>>, TError,{sessionId: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof extendSession>>, TError,{sessionId: string}, TContext> => {

const mutationKey = ['extendSession'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof extendSession>>, {sessionId: string}> = (props) => {
          const {sessionId} = props ?? {};

          return  extendSession(sessionId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ExtendSessionMutationResult = NonNullable<Awaited<ReturnType<typeof extendSession>>>
    
    export type ExtendSessionMutationError = AxiosError<GuestSessionResponse>

    /**
 * @summary Extend guest session
 */
export const useExtendSession = <TError = AxiosError<GuestSessionResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof extendSession>>, TError,{sessionId: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof extendSession>>,
        TError,
        {sessionId: string},
        TContext
      > => {

      const mutationOptions = getExtendSessionMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * Save a PC build configuration for a guest session
 * @summary Save guest build
 */
export const saveBuild = (
    guestBuildRequest: GuestBuildRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GuestBuildResponse>> => {
    
    
    return axios.default.post(
      `/api/v1/guest/builds`,
      guestBuildRequest,options
    );
  }



export const getSaveBuildMutationOptions = <TError = AxiosError<GuestBuildResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof saveBuild>>, TError,{data: GuestBuildRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof saveBuild>>, TError,{data: GuestBuildRequest}, TContext> => {

const mutationKey = ['saveBuild'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof saveBuild>>, {data: GuestBuildRequest}> = (props) => {
          const {data} = props ?? {};

          return  saveBuild(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SaveBuildMutationResult = NonNullable<Awaited<ReturnType<typeof saveBuild>>>
    export type SaveBuildMutationBody = GuestBuildRequest
    export type SaveBuildMutationError = AxiosError<GuestBuildResponse>

    /**
 * @summary Save guest build
 */
export const useSaveBuild = <TError = AxiosError<GuestBuildResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof saveBuild>>, TError,{data: GuestBuildRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof saveBuild>>,
        TError,
        {data: GuestBuildRequest},
        TContext
      > => {

      const mutationOptions = getSaveBuildMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * Validate if a guest session is still active and refresh it
 * @summary Validate guest session
 */
export const validateSession = (
    sessionId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GuestSessionResponse>> => {
    
    
    return axios.default.get(
      `/api/v1/guest/session/${sessionId}`,options
    );
  }


export const getValidateSessionQueryKey = (sessionId?: string,) => {
    return [`/api/v1/guest/session/${sessionId}`] as const;
    }

    
export const getValidateSessionQueryOptions = <TData = Awaited<ReturnType<typeof validateSession>>, TError = AxiosError<GuestSessionResponse>>(sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof validateSession>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getValidateSessionQueryKey(sessionId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof validateSession>>> = ({ signal }) => validateSession(sessionId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(sessionId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof validateSession>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ValidateSessionQueryResult = NonNullable<Awaited<ReturnType<typeof validateSession>>>
export type ValidateSessionQueryError = AxiosError<GuestSessionResponse>


export function useValidateSession<TData = Awaited<ReturnType<typeof validateSession>>, TError = AxiosError<GuestSessionResponse>>(
 sessionId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof validateSession>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof validateSession>>,
          TError,
          Awaited<ReturnType<typeof validateSession>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useValidateSession<TData = Awaited<ReturnType<typeof validateSession>>, TError = AxiosError<GuestSessionResponse>>(
 sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof validateSession>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof validateSession>>,
          TError,
          Awaited<ReturnType<typeof validateSession>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useValidateSession<TData = Awaited<ReturnType<typeof validateSession>>, TError = AxiosError<GuestSessionResponse>>(
 sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof validateSession>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Validate guest session
 */

export function useValidateSession<TData = Awaited<ReturnType<typeof validateSession>>, TError = AxiosError<GuestSessionResponse>>(
 sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof validateSession>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getValidateSessionQueryOptions(sessionId,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Delete a guest session and all its associated builds
 * @summary Delete guest session
 */
export const deleteSession = (
    sessionId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<MessageResponse>> => {
    
    
    return axios.default.delete(
      `/api/v1/guest/session/${sessionId}`,options
    );
  }



export const getDeleteSessionMutationOptions = <TError = AxiosError<MessageResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSession>>, TError,{sessionId: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteSession>>, TError,{sessionId: string}, TContext> => {

const mutationKey = ['deleteSession'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteSession>>, {sessionId: string}> = (props) => {
          const {sessionId} = props ?? {};

          return  deleteSession(sessionId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteSessionMutationResult = NonNullable<Awaited<ReturnType<typeof deleteSession>>>
    
    export type DeleteSessionMutationError = AxiosError<MessageResponse>

    /**
 * @summary Delete guest session
 */
export const useDeleteSession = <TError = AxiosError<MessageResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSession>>, TError,{sessionId: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteSession>>,
        TError,
        {sessionId: string},
        TContext
      > => {

      const mutationOptions = getDeleteSessionMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * Retrieve all builds for a specific guest session
 * @summary Get builds by session
 */
export const getBuildsBySession = (
    sessionId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GuestBuildResponse[]>> => {
    
    
    return axios.default.get(
      `/api/v1/guest/session/${sessionId}/builds`,options
    );
  }


export const getGetBuildsBySessionQueryKey = (sessionId?: string,) => {
    return [`/api/v1/guest/session/${sessionId}/builds`] as const;
    }

    
export const getGetBuildsBySessionQueryOptions = <TData = Awaited<ReturnType<typeof getBuildsBySession>>, TError = AxiosError<unknown>>(sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBuildsBySession>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetBuildsBySessionQueryKey(sessionId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBuildsBySession>>> = ({ signal }) => getBuildsBySession(sessionId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(sessionId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getBuildsBySession>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetBuildsBySessionQueryResult = NonNullable<Awaited<ReturnType<typeof getBuildsBySession>>>
export type GetBuildsBySessionQueryError = AxiosError<unknown>


export function useGetBuildsBySession<TData = Awaited<ReturnType<typeof getBuildsBySession>>, TError = AxiosError<unknown>>(
 sessionId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBuildsBySession>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBuildsBySession>>,
          TError,
          Awaited<ReturnType<typeof getBuildsBySession>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBuildsBySession<TData = Awaited<ReturnType<typeof getBuildsBySession>>, TError = AxiosError<unknown>>(
 sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBuildsBySession>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBuildsBySession>>,
          TError,
          Awaited<ReturnType<typeof getBuildsBySession>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBuildsBySession<TData = Awaited<ReturnType<typeof getBuildsBySession>>, TError = AxiosError<unknown>>(
 sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBuildsBySession>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get builds by session
 */

export function useGetBuildsBySession<TData = Awaited<ReturnType<typeof getBuildsBySession>>, TError = AxiosError<unknown>>(
 sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBuildsBySession>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetBuildsBySessionQueryOptions(sessionId,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Retrieve the most recent build for a guest session
 * @summary Get latest build for session
 */
export const getLatestBuild = (
    sessionId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GuestBuildResponse>> => {
    
    
    return axios.default.get(
      `/api/v1/guest/session/${sessionId}/builds/latest`,options
    );
  }


export const getGetLatestBuildQueryKey = (sessionId?: string,) => {
    return [`/api/v1/guest/session/${sessionId}/builds/latest`] as const;
    }

    
export const getGetLatestBuildQueryOptions = <TData = Awaited<ReturnType<typeof getLatestBuild>>, TError = AxiosError<GuestBuildResponse>>(sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLatestBuild>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLatestBuildQueryKey(sessionId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLatestBuild>>> = ({ signal }) => getLatestBuild(sessionId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(sessionId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLatestBuild>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLatestBuildQueryResult = NonNullable<Awaited<ReturnType<typeof getLatestBuild>>>
export type GetLatestBuildQueryError = AxiosError<GuestBuildResponse>


export function useGetLatestBuild<TData = Awaited<ReturnType<typeof getLatestBuild>>, TError = AxiosError<GuestBuildResponse>>(
 sessionId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLatestBuild>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLatestBuild>>,
          TError,
          Awaited<ReturnType<typeof getLatestBuild>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLatestBuild<TData = Awaited<ReturnType<typeof getLatestBuild>>, TError = AxiosError<GuestBuildResponse>>(
 sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLatestBuild>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLatestBuild>>,
          TError,
          Awaited<ReturnType<typeof getLatestBuild>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLatestBuild<TData = Awaited<ReturnType<typeof getLatestBuild>>, TError = AxiosError<GuestBuildResponse>>(
 sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLatestBuild>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get latest build for session
 */

export function useGetLatestBuild<TData = Awaited<ReturnType<typeof getLatestBuild>>, TError = AxiosError<GuestBuildResponse>>(
 sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLatestBuild>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLatestBuildQueryOptions(sessionId,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



