/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * RigArchitect API
 * API documentation for RigArchitect application
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AuthenticateUser200,
  AuthenticateUser401,
  AuthenticateUser404,
  ChangePassword200,
  ChangePassword400,
  ChangePassword401,
  ChangePasswordRequest,
  GuestToUserMigrationRequest,
  LoginRequest,
  LogoutUser200,
  MigrateGuestData200,
  MigrateGuestData400,
  MigrateGuestData401,
  RefreshToken200,
  RefreshToken401,
  RefreshTokenRequest,
  RegisterUser201,
  RegisterUser400,
  RegisterUser409,
  SignupRequest,
  VerifyToken200,
  VerifyToken401
} from '.././model';





/**
 * Create a new user account with email and password
 * @summary Register new user
 */
export const registerUser = (
    signupRequest: SignupRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<RegisterUser201>> => {
    
    
    return axios.default.post(
      `/api/v1/auth/signup`,
      signupRequest,options
    );
  }



export const getRegisterUserMutationOptions = <TError = AxiosError<RegisterUser400 | RegisterUser409>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerUser>>, TError,{data: SignupRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof registerUser>>, TError,{data: SignupRequest}, TContext> => {

const mutationKey = ['registerUser'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof registerUser>>, {data: SignupRequest}> = (props) => {
          const {data} = props ?? {};

          return  registerUser(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RegisterUserMutationResult = NonNullable<Awaited<ReturnType<typeof registerUser>>>
    export type RegisterUserMutationBody = SignupRequest
    export type RegisterUserMutationError = AxiosError<RegisterUser400 | RegisterUser409>

    /**
 * @summary Register new user
 */
export const useRegisterUser = <TError = AxiosError<RegisterUser400 | RegisterUser409>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerUser>>, TError,{data: SignupRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof registerUser>>,
        TError,
        {data: SignupRequest},
        TContext
      > => {

      const mutationOptions = getRegisterUserMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * Use refresh token to obtain a new access token
 * @summary Refresh access token
 */
export const refreshToken = (
    refreshTokenRequest: RefreshTokenRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<RefreshToken200>> => {
    
    
    return axios.default.post(
      `/api/v1/auth/refresh`,
      refreshTokenRequest,options
    );
  }



export const getRefreshTokenMutationOptions = <TError = AxiosError<RefreshToken401>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refreshToken>>, TError,{data: RefreshTokenRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof refreshToken>>, TError,{data: RefreshTokenRequest}, TContext> => {

const mutationKey = ['refreshToken'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof refreshToken>>, {data: RefreshTokenRequest}> = (props) => {
          const {data} = props ?? {};

          return  refreshToken(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RefreshTokenMutationResult = NonNullable<Awaited<ReturnType<typeof refreshToken>>>
    export type RefreshTokenMutationBody = RefreshTokenRequest
    export type RefreshTokenMutationError = AxiosError<RefreshToken401>

    /**
 * @summary Refresh access token
 */
export const useRefreshToken = <TError = AxiosError<RefreshToken401>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refreshToken>>, TError,{data: RefreshTokenRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof refreshToken>>,
        TError,
        {data: RefreshTokenRequest},
        TContext
      > => {

      const mutationOptions = getRefreshTokenMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * Migrate guest session builds to user account
 * @summary Migrate guest data
 */
export const migrateGuestData = (
    guestToUserMigrationRequest: GuestToUserMigrationRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<MigrateGuestData200>> => {
    
    
    return axios.default.post(
      `/api/v1/auth/migrate-guest`,
      guestToUserMigrationRequest,options
    );
  }



export const getMigrateGuestDataMutationOptions = <TError = AxiosError<MigrateGuestData400 | MigrateGuestData401>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof migrateGuestData>>, TError,{data: GuestToUserMigrationRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof migrateGuestData>>, TError,{data: GuestToUserMigrationRequest}, TContext> => {

const mutationKey = ['migrateGuestData'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof migrateGuestData>>, {data: GuestToUserMigrationRequest}> = (props) => {
          const {data} = props ?? {};

          return  migrateGuestData(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type MigrateGuestDataMutationResult = NonNullable<Awaited<ReturnType<typeof migrateGuestData>>>
    export type MigrateGuestDataMutationBody = GuestToUserMigrationRequest
    export type MigrateGuestDataMutationError = AxiosError<MigrateGuestData400 | MigrateGuestData401>

    /**
 * @summary Migrate guest data
 */
export const useMigrateGuestData = <TError = AxiosError<MigrateGuestData400 | MigrateGuestData401>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof migrateGuestData>>, TError,{data: GuestToUserMigrationRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof migrateGuestData>>,
        TError,
        {data: GuestToUserMigrationRequest},
        TContext
      > => {

      const mutationOptions = getMigrateGuestDataMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * Logout current user (client should discard tokens)
 * @summary Logout user
 */
export const logoutUser = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<LogoutUser200>> => {
    
    
    return axios.default.post(
      `/api/v1/auth/logout`,undefined,options
    );
  }



export const getLogoutUserMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logoutUser>>, TError,void, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof logoutUser>>, TError,void, TContext> => {

const mutationKey = ['logoutUser'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof logoutUser>>, void> = () => {
          

          return  logoutUser(axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LogoutUserMutationResult = NonNullable<Awaited<ReturnType<typeof logoutUser>>>
    
    export type LogoutUserMutationError = AxiosError<unknown>

    /**
 * @summary Logout user
 */
export const useLogoutUser = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logoutUser>>, TError,void, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof logoutUser>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getLogoutUserMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * Login with email and password to receive JWT tokens
 * @summary Authenticate user
 */
export const authenticateUser = (
    loginRequest: LoginRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AuthenticateUser200>> => {
    
    
    return axios.default.post(
      `/api/v1/auth/login`,
      loginRequest,options
    );
  }



export const getAuthenticateUserMutationOptions = <TError = AxiosError<AuthenticateUser401 | AuthenticateUser404>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authenticateUser>>, TError,{data: LoginRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof authenticateUser>>, TError,{data: LoginRequest}, TContext> => {

const mutationKey = ['authenticateUser'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authenticateUser>>, {data: LoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  authenticateUser(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthenticateUserMutationResult = NonNullable<Awaited<ReturnType<typeof authenticateUser>>>
    export type AuthenticateUserMutationBody = LoginRequest
    export type AuthenticateUserMutationError = AxiosError<AuthenticateUser401 | AuthenticateUser404>

    /**
 * @summary Authenticate user
 */
export const useAuthenticateUser = <TError = AxiosError<AuthenticateUser401 | AuthenticateUser404>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authenticateUser>>, TError,{data: LoginRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authenticateUser>>,
        TError,
        {data: LoginRequest},
        TContext
      > => {

      const mutationOptions = getAuthenticateUserMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * Change password for authenticated user
 * @summary Change password
 */
export const changePassword = (
    changePasswordRequest: ChangePasswordRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ChangePassword200>> => {
    
    
    return axios.default.post(
      `/api/v1/auth/change-password`,
      changePasswordRequest,options
    );
  }



export const getChangePasswordMutationOptions = <TError = AxiosError<ChangePassword400 | ChangePassword401>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changePassword>>, TError,{data: ChangePasswordRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof changePassword>>, TError,{data: ChangePasswordRequest}, TContext> => {

const mutationKey = ['changePassword'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof changePassword>>, {data: ChangePasswordRequest}> = (props) => {
          const {data} = props ?? {};

          return  changePassword(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ChangePasswordMutationResult = NonNullable<Awaited<ReturnType<typeof changePassword>>>
    export type ChangePasswordMutationBody = ChangePasswordRequest
    export type ChangePasswordMutationError = AxiosError<ChangePassword400 | ChangePassword401>

    /**
 * @summary Change password
 */
export const useChangePassword = <TError = AxiosError<ChangePassword400 | ChangePassword401>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changePassword>>, TError,{data: ChangePasswordRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof changePassword>>,
        TError,
        {data: ChangePasswordRequest},
        TContext
      > => {

      const mutationOptions = getChangePasswordMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * Verify if the current JWT token is valid
 * @summary Verify token
 */
export const verifyToken = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<VerifyToken200>> => {
    
    
    return axios.default.get(
      `/api/v1/auth/verify`,options
    );
  }


export const getVerifyTokenQueryKey = () => {
    return [`/api/v1/auth/verify`] as const;
    }

    
export const getVerifyTokenQueryOptions = <TData = Awaited<ReturnType<typeof verifyToken>>, TError = AxiosError<VerifyToken401>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof verifyToken>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getVerifyTokenQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof verifyToken>>> = ({ signal }) => verifyToken({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof verifyToken>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type VerifyTokenQueryResult = NonNullable<Awaited<ReturnType<typeof verifyToken>>>
export type VerifyTokenQueryError = AxiosError<VerifyToken401>


export function useVerifyToken<TData = Awaited<ReturnType<typeof verifyToken>>, TError = AxiosError<VerifyToken401>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof verifyToken>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof verifyToken>>,
          TError,
          Awaited<ReturnType<typeof verifyToken>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useVerifyToken<TData = Awaited<ReturnType<typeof verifyToken>>, TError = AxiosError<VerifyToken401>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof verifyToken>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof verifyToken>>,
          TError,
          Awaited<ReturnType<typeof verifyToken>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useVerifyToken<TData = Awaited<ReturnType<typeof verifyToken>>, TError = AxiosError<VerifyToken401>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof verifyToken>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Verify token
 */

export function useVerifyToken<TData = Awaited<ReturnType<typeof verifyToken>>, TError = AxiosError<VerifyToken401>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof verifyToken>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getVerifyTokenQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



