/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * RigArchitect API
 * API documentation for RigArchitect application
 * OpenAPI spec version: 1.0
 */

/**
 * Request DTO for updating a user's budget
 */
export interface BudgetUpdateRequest {
  /**
   * New budget amount in USD
   * @minimum 0
   */
  budget: number;
}
