/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * RigArchitect API
 * API documentation for RigArchitect application
 * OpenAPI spec version: 1.0
 */

/**
 * Status of the build cart
 */
export type BuildCartResponseStatus = typeof BuildCartResponseStatus[keyof typeof BuildCartResponseStatus];


export const BuildCartResponseStatus = {
  DRAFT: 'DRAFT',
  ACTIVE: 'ACTIVE',
  FINALIZED: 'FINALIZED',
  CANCELLED: 'CANCELLED',
} as const;
