/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * RigArchitect API
 * API documentation for RigArchitect application
 * OpenAPI spec version: 1.0
 */
import type { BuildCartResponseStatus } from './buildCartResponseStatus';

/**
 * Response DTO representing a build cart
 */
export interface BuildCartResponse {
  /** Unique identifier of the build cart */
  id?: number;
  /** ID of the user who owns the cart */
  userId?: number;
  /** Name of the build cart */
  name?: string;
  /** Status of the build cart */
  status?: BuildCartResponseStatus;
  /** Total price of all components in the cart */
  totalPrice?: number;
  /** Timestamp when the build cart was created */
  createdAt?: string;
  /** Timestamp when the build cart was last updated */
  updatedAt?: string;
  /** Timestamp when the build cart was finalized, if applicable */
  finalizedAt?: string;
}
