/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * RigArchitect API
 * API documentation for RigArchitect application
 * OpenAPI spec version: 1.0
 */
import type { BuildCartRequestStatus } from './buildCartRequestStatus';

/**
 * Request DTO for creating or updating a build cart
 */
export interface BuildCartRequest {
  /** Name of the build cart */
  name: string;
  /** Status of the build cart */
  status: BuildCartRequestStatus;
}
