/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * RigArchitect API
 * API documentation for RigArchitect application
 * OpenAPI spec version: 1.0
 */

/**
 * Request DTO for updating the quantity of an existing cart item
 */
export interface CartItemUpdate {
  /**
   * New quantity for the cart item
   * @minimum 1
   */
  quantity: number;
}
