/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * RigArchitect API
 * API documentation for RigArchitect application
 * OpenAPI spec version: 1.0
 */

/**
 * Request DTO for creating a new item in a build cart
 */
export interface CartItemRequest {
  /** ID of the build cart this item belongs to */
  cartId: number;
  /** ID of the component being added */
  componentId: number;
  /**
   * Quantity of the component in the cart
   * @minimum 1
   */
  quantity: number;
}
