/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * RigArchitect API
 * API documentation for RigArchitect application
 * OpenAPI spec version: 1.0
 */

/**
 * Response DTO representing an item in a build cart
 */
export interface CartItemResponse {
  /** Unique identifier of the cart item */
  id?: number;
  /** ID of the cart this item belongs to */
  cartId?: number;
  /** ID of the component */
  componentId?: number;
  /** Name of the component */
  componentName?: string;
  /** Quantity of the component in the cart */
  quantity?: number;
  /** Timestamp when the cart item was created */
  createdAt?: string;
  /** Timestamp when the cart item was last updated */
  updatedAt?: string;
}
