/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * RigArchitect API
 * API documentation for RigArchitect application
 * OpenAPI spec version: 1.0
 */

/**
 * Request DTO for changing user password
 */
export interface ChangePasswordRequest {
  /** Current password for verification */
  currentPassword: string;
  /**
   * New password
   * @minLength 6
   * @maxLength 100
   */
  newPassword: string;
}
