/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * RigArchitect API
 * API documentation for RigArchitect application
 * OpenAPI spec version: 1.0
 */

/**
 * Flexible JSON object for additional compatibility data
 */
export type ComponentRequestExtraCompatibility = {[key: string]: { [key: string]: unknown }};
