/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * RigArchitect API
 * API documentation for RigArchitect application
 * OpenAPI spec version: 1.0
 */

/**
 * Metadata for performance and template matching
 */
export type ComponentResponseMetadata = {[key: string]: { [key: string]: unknown }};
