/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * RigArchitect API
 * API documentation for RigArchitect application
 * OpenAPI spec version: 1.0
 */
import type { ComponentRequestType } from './componentRequestType';
import type { ComponentRequestExtraCompatibility } from './componentRequestExtraCompatibility';
import type { ComponentRequestMetadata } from './componentRequestMetadata';

/**
 * Request DTO for creating or updating a PC component
 */
export interface ComponentRequest {
  /** Component name */
  name: string;
  /** Brand of the component */
  brand: string;
  /** Type of component */
  type: ComponentRequestType;
  /** Compatibility tag */
  compatibilityTag: string;
  /**
   * Price of the component in USD
   * @minimum 0
   * @exclusiveMinimum
   */
  price: number;
  /**
   * Number of items in stock
   * @minimum 0
   */
  stockQuantity: number;
  /** CPU socket type, if applicable */
  socket?: string;
  /** RAM type, if applicable */
  ramType?: string;
  /**
   * Power consumption in watts
   * @minimum 0
   */
  wattage?: number;
  /** Form factor of the component, if applicable */
  formFactor?: string;
  /**
   * GPU length in mm, if applicable
   * @minimum 0
   */
  gpuLengthMm?: number;
  /**
   * Cooler height in mm, if applicable
   * @minimum 0
   */
  coolerHeightMm?: number;
  /** PSU form factor, if applicable */
  psuFormFactor?: string;
  /**
   * PCI slots required, if applicable
   * @minimum 0
   */
  pciSlotsRequired?: number;
  /** Flexible JSON object for additional compatibility data */
  extraCompatibility?: ComponentRequestExtraCompatibility;
  /** Metadata for performance and template matching */
  metadata?: ComponentRequestMetadata;
}
