/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * RigArchitect API
 * API documentation for RigArchitect application
 * OpenAPI spec version: 1.0
 */
import type { ComponentResponseType } from './componentResponseType';
import type { ComponentResponseExtraCompatibility } from './componentResponseExtraCompatibility';
import type { ComponentResponseMetadata } from './componentResponseMetadata';

/**
 * Response DTO representing a PC component
 */
export interface ComponentResponse {
  /** Unique identifier of the component */
  id?: number;
  /** Component name */
  name?: string;
  /** Brand of the component */
  brand?: string;
  /** Type of component */
  type?: ComponentResponseType;
  /** Compatibility tag */
  compatibilityTag?: string;
  /** Price of the component in USD */
  price?: number;
  /** Number of items in stock */
  stockQuantity?: number;
  /** CPU socket type, if applicable */
  socket?: string;
  /** RAM type, if applicable */
  ramType?: string;
  /** Power consumption in watts */
  wattage?: number;
  /** Form factor of the component, if applicable */
  formFactor?: string;
  /** GPU length in mm, if applicable */
  gpuLengthMm?: number;
  /** Cooler height in mm, if applicable */
  coolerHeightMm?: number;
  /** PSU form factor, if applicable */
  psuFormFactor?: string;
  /** PCI slots required, if applicable */
  pciSlotsRequired?: number;
  /** Flexible JSON object for additional compatibility data */
  extraCompatibility?: ComponentResponseExtraCompatibility;
  /** Metadata for performance and template matching */
  metadata?: ComponentResponseMetadata;
  /** Timestamp when the component was created */
  createdAt?: string;
  /** Timestamp when the component was last updated */
  updatedAt?: string;
}
