/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * RigArchitect API
 * API documentation for RigArchitect application
 * OpenAPI spec version: 1.0
 */

/**
 * Type of component
 */
export type ComponentRequestType = typeof ComponentRequestType[keyof typeof ComponentRequestType];


export const ComponentRequestType = {
  CPU: 'CPU',
  GPU: 'GPU',
  RAM: 'RAM',
  SSD: 'SSD',
  HDD: 'HDD',
  Motherboard: 'Motherboard',
  PSU: 'PSU',
  Case: 'Case',
  Cooler: 'Cooler',
} as const;
