/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * RigArchitect API
 * API documentation for RigArchitect application
 * OpenAPI spec version: 1.0
 */
import type { GetAllComponentsType } from './getAllComponentsType';

export type GetAllComponentsParams = {
/**
 * Page number (0-indexed)
 */
page?: number;
/**
 * Page size
 */
size?: number;
/**
 * Sort field
 */
sortBy?: string;
/**
 * Sort direction (asc/desc)
 */
sortDir?: string;
/**
 * Filter by type
 */
type?: GetAllComponentsType;
/**
 * Filter by brand
 */
brand?: string;
/**
 * Search term for name/brand
 */
search?: string;
/**
 * Filter by compatibility tag
 */
compatibilityTag?: string;
/**
 * Maximum price filter
 */
maxPrice?: number;
/**
 * Minimum stock quantity
 */
minStock?: number;
/**
 * Only show in-stock items
 */
inStockOnly?: boolean;
};
