/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * RigArchitect API
 * API documentation for RigArchitect application
 * OpenAPI spec version: 1.0
 */

export type GetComponentsByTypeParams = {
/**
 * Page number (0-indexed)
 */
page?: number;
/**
 * Page size
 */
size?: number;
/**
 * Sort field
 */
sortBy?: string;
/**
 * Sort direction (asc/desc)
 */
sortDir?: string;
};
