/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * RigArchitect API
 * API documentation for RigArchitect application
 * OpenAPI spec version: 1.0
 */

/**
 * Request DTO for creating or updating a guest build
 */
export interface GuestBuildRequest {
  /** Session identifier */
  sessionId: string;
  /** Build configuration data as JSON string */
  buildData: string;
}
