/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * RigArchitect API
 * API documentation for RigArchitect application
 * OpenAPI spec version: 1.0
 */

/**
 * Response DTO for guest build information
 */
export interface GuestBuildResponse {
  /** Unique build ID */
  id?: number;
  /** Session identifier */
  sessionId?: string;
  /** Build configuration data as JSON string */
  buildData?: string;
  /** Build creation timestamp */
  createdAt?: string;
  /** Build last updated timestamp */
  updatedAt?: string;
}
