/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * RigArchitect API
 * API documentation for RigArchitect application
 * OpenAPI spec version: 1.0
 */

/**
 * Response DTO for guest session information
 */
export interface GuestSessionResponse {
  /** Unique session UUID */
  id?: string;
  /** Session identifier */
  sessionId?: string;
  /** Session creation timestamp */
  createdAt?: string;
  /** Session expiration timestamp */
  expiresAt?: string;
  /** Last accessed timestamp */
  lastAccessed?: string;
  /** Whether session is expired */
  isExpired?: boolean;
}
