/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * RigArchitect API
 * API documentation for RigArchitect application
 * OpenAPI spec version: 1.0
 */

/**
 * Request DTO for user authentication
 */
export interface LoginRequest {
  /** Email address of the user */
  email: string;
  /**
   * Password for authentication
   * @minLength 6
   * @maxLength 100
   */
  password: string;
}
