/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * RigArchitect API
 * API documentation for RigArchitect application
 * OpenAPI spec version: 1.0
 */
import type { ComponentResponse } from './componentResponse';
import type { SortObject } from './sortObject';
import type { PageableObject } from './pageableObject';

export interface PageComponentResponse {
  totalPages?: number;
  totalElements?: number;
  size?: number;
  content?: ComponentResponse[];
  number?: number;
  sort?: SortObject;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  pageable?: PageableObject;
  empty?: boolean;
}
