/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * RigArchitect API
 * API documentation for RigArchitect application
 * OpenAPI spec version: 1.0
 */
import type { ComponentResponse } from './componentResponse';

export interface PagedResponseComponentResponse {
  content?: ComponentResponse[];
  totalElements?: number;
  totalPages?: number;
  currentPage?: number;
  size?: number;
  hasNext?: boolean;
  hasPrevious?: boolean;
  isFirst?: boolean;
  isLast?: boolean;
}
