/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * RigArchitect API
 * API documentation for RigArchitect application
 * OpenAPI spec version: 1.0
 */

/**
 * Request DTO for refreshing JWT access token
 */
export interface RefreshTokenRequest {
  /** Refresh token used to obtain new access token */
  refreshToken: string;
}
