/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * RigArchitect API
 * API documentation for RigArchitect application
 * OpenAPI spec version: 1.0
 */
import type { SearchComponentsPagedType } from './searchComponentsPagedType';

export type SearchComponentsPagedParams = {
/**
 * Search term (name, brand, etc.)
 */
searchTerm?: string;
/**
 * Type filter
 */
type?: SearchComponentsPagedType;
/**
 * Brand filter
 */
brand?: string;
/**
 * Socket filter
 */
socket?: string;
/**
 * Compatibility tag filter
 */
compatibilityTag?: string;
/**
 * Maximum price filter
 */
maxPrice?: number;
/**
 * Minimum stock filter
 */
minStock?: number;
/**
 * In stock only filter
 */
inStockOnly?: boolean;
/**
 * Page number (0-based)
 */
page?: number;
/**
 * Page size
 */
size?: number;
/**
 * Sort field
 */
sortBy?: string;
/**
 * Sort direction (asc/desc)
 */
sortDirection?: string;
};
