/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * RigArchitect API
 * API documentation for RigArchitect application
 * OpenAPI spec version: 1.0
 */

export type SearchComponentsPagedType = typeof SearchComponentsPagedType[keyof typeof SearchComponentsPagedType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SearchComponentsPagedType = {
  CPU: 'CPU',
  GPU: 'GPU',
  RAM: 'RAM',
  SSD: 'SSD',
  HDD: 'HDD',
  Motherboard: 'Motherboard',
  PSU: 'PSU',
  Case: 'Case',
  Cooler: 'Cooler',
} as const;
