/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * RigArchitect API
 * API documentation for RigArchitect application
 * OpenAPI spec version: 1.0
 */
import type { SearchComponentsType } from './searchComponentsType';

export type SearchComponentsParams = {
/**
 * Type filter
 */
type?: SearchComponentsType;
/**
 * Brand filter
 */
brand?: string;
/**
 * Socket filter
 */
socket?: string;
/**
 * Maximum price filter
 */
maxPrice?: number;
/**
 * Minimum stock filter
 */
minStock?: number;
};
