/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * RigArchitect API
 * API documentation for RigArchitect application
 * OpenAPI spec version: 1.0
 */

/**
 * Request DTO for user registration
 */
export interface SignupRequest {
  /**
   * Full name of the user
   * @minLength 2
   * @maxLength 100
   */
  name: string;
  /** Email address of the user */
  email: string;
  /**
   * Password for the new account
   * @minLength 6
   * @maxLength 100
   */
  password: string;
  /**
   * Initial budget for the user in USD
   * @minimum 0
   * @maximum 999999.99
   */
  budget?: number;
}
