/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * RigArchitect API
 * API documentation for RigArchitect application
 * OpenAPI spec version: 1.0
 */

/**
 * Response DTO representing a user
 */
export interface UserResponse {
  /** Unique identifier of the user */
  id?: number;
  /** Full name of the user */
  name?: string;
  /** Email address of the user */
  email?: string;
  /** Budget of the user in USD */
  budget?: number;
  /** Timestamp when the user was created */
  createdAt?: string;
  /** Timestamp when the user was last updated */
  updatedAt?: string;
}
