/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * RigArchitect API
 * API documentation for RigArchitect application
 * OpenAPI spec version: 1.0
 */

/**
 * Request DTO for creating or updating a user
 */
export interface UserRequest {
  /** Full name of the user */
  name: string;
  /** Email address of the user */
  email: string;
  /**
   * Budget of the user in USD
   * @minimum 0
   */
  budget: number;
}
